<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ButtonHMI" Id="{7289cd62-48f7-497b-b98c-a40c2e2036a6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK INTERNAL ABSTRACT ButtonHMI
VAR_INPUT
    inDisable : BOOL; // disable the button and show the 'disable' state of the button
    inOn      : BOOL; // show the 'on' state of the button
    inError   : BOOL; // show the 'error' state of the button
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _button  : BOOL; // link this variable to the output of your HMI button
    _disable : BOOL; // link this variable to the 'disable' input of your HMI button
    _on      : BOOL; // link this variable to the 'on' input of your HMI button
    _error   : BOOL; // link this variable to the 'error' or 'alarm' input of your HMI button
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="SetButton" Id="{602095fb-547a-46d5-9a25-cffdad52fe59}">
      <Declaration><![CDATA[/// Set the internal button state
/// used to bypass the HMI action
METHOD PUBLIC SetButton
VAR_INPUT
    value : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^._button := value;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>